name: Pi != 4

on:
  push:
    branches:
      - main

jobs:
  revert_bad_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get commit message
        id: commit_message
        run: |
          banned_word="Troll"  # Remplace par le mot à interdire
          commits=$(git log -1 --pretty=%B)
          
          if echo "$commits" | grep -i "$banned_word"; then
            echo "Found banned word in commit message: $banned_word"
            echo "contains_banned_word=true" >> $GITHUB_ENV
          else
            echo "No banned word found."
            echo "contains_banned_word=false" >> $GITHUB_ENV
          fi

      - name: Set Git user info
        if: env.contains_banned_word == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Revert commit if it contains banned word
        if: env.contains_banned_word == 'true'
        run: |
          echo "Reverting the last commit due to banned word"
          git revert --no-edit HEAD
          git push origin main
