name: PI != 4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Check commit messages for banned words
        run: |
          banned_word="Troll"
          commits=$(git log --format=%B --no-merges -n 10)
          if echo "$commits" | grep -i "$banned_word"; then
            echo "Error: pi != 4"
            exit 1
          fi
