name: Pi != 4

on:
  push:
    branches:
      - main

jobs:
  revert_bad_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get commit message
        id: commit_message
        run: |
          banned_word="Troll"  # Remplace par le mot à interdire
          commits=$(git log -1 --pretty=%B)
          
          if echo "$commits" | grep -i "$banned_word"; then
            echo "Found banned word in commit message: $banned_word"
            echo "::set-output name=contains_banned_word::true"
          else
            echo "No banned word found."
            echo "::set-output name=contains_banned_word::false"

      - name: Revert commit if it contains banned word
        if: steps.commit_message.outputs.contains_banned_word == 'true'
        run: |
          echo "Reverting the last commit due to banned word"
          git revert -m"pi != 4" --no-edit HEAD
          git push origin main
